import React, { useCallback, useEffect, useRef, useState } from 'react';
import { ArrowLeft, CheckCircle2, Music, Pause, Play, RotateCcw, SkipForward, Volume2 } from 'lucide-react';
import type { Workout } from '../types';
import { MovementAnimation } from './MovementAnimation';
import { getSpotifyLink, openSpotify } from '../spotify';

type Phase = 'ready' | 'work' | 'rest' | 'done';
interface Props { workout: Workout; onExit: () => void; onStart: (startedAt: string) => void; onComplete: (startedAt: string, endedAt: string) => void; }
const say = (text: string) => { if (!('speechSynthesis' in window)) return; window.speechSynthesis.cancel(); const u = new SpeechSynthesisUtterance(text); u.lang = 'it-IT'; u.rate = .98; u.volume = 1; window.speechSynthesis.speak(u); };
const beep = () => { try { const Ctx = window.AudioContext || (window as unknown as { webkitAudioContext: typeof AudioContext }).webkitAudioContext; const c = new Ctx(); const o = c.createOscillator(); const g = c.createGain(); o.frequency.value = 880; g.gain.value = .08; o.connect(g); g.connect(c.destination); o.start(); o.stop(c.currentTime + .12); } catch { /* audio is optional */ } };

export const GuidedTimer: React.FC<Props> = ({ workout, onExit, onStart, onComplete }) => {
  const [idx, setIdx] = useState(0), [setNo, setSetNo] = useState(1), [phase, setPhase] = useState<Phase>('ready'), [left, setLeft] = useState(5), [running, setRunning] = useState(false);
  const announced = useRef(''); const startedAt = useRef<string | null>(null); const exercise = workout.exercises[idx];
  const announce = useCallback((p: Phase, sec: number) => { const key = `${idx}-${setNo}-${p}`; if (announced.current === key) return; announced.current = key; if (p === 'ready') say(`Preparati. ${exercise.name}. ${exercise.prescription}. Serie ${setNo} di ${exercise.sets}`); if (p === 'work') { beep(); say(`Via. ${exercise.name}. ${exercise.prescription}`); } if (p === 'rest') say(`Stop. Recupero ${sec} secondi`); if (p === 'done') say('Allenamento completato. Ottimo lavoro.'); }, [exercise, idx, setNo]);
  const next = useCallback(() => { if (phase === 'ready') { setPhase('work'); setLeft(exercise.work); return; } if (phase === 'work' && exercise.rest > 0) { setPhase('rest'); setLeft(exercise.rest); return; } if ((phase === 'work' || phase === 'rest') && setNo < exercise.sets) { setSetNo(n => n + 1); setPhase('ready'); setLeft(5); return; } if (idx < workout.exercises.length - 1) { setIdx(n => n + 1); setSetNo(1); setPhase('ready'); setLeft(8); return; } setPhase('done'); setRunning(false); const end = new Date().toISOString(); onComplete(startedAt.current ?? end, end); }, [phase, exercise, setNo, idx, workout.exercises.length, onComplete]);
  useEffect(() => { announce(phase, left); }, [phase, announce, left]);
  useEffect(() => { if (!running || phase === 'done') return; const t = window.setInterval(() => setLeft(v => { if (v <= 1) { window.clearInterval(t); window.setTimeout(next, 0); return 0; } if (v === 11) say('10 secondi'); if (v === 4) { beep(); say('3, 2, 1'); } return v - 1; }), 1000); return () => window.clearInterval(t); }, [running, phase, next]);
  const start = () => { const isFirstStart = !startedAt.current; if (!startedAt.current) { startedAt.current = new Date().toISOString(); onStart(startedAt.current); } setRunning(true); say(`Inizio allenamento. ${workout.title}. Preparati.`); if (isFirstStart) openSpotify(); try { (navigator as Navigator & { wakeLock?: { request: (type: 'screen') => Promise<unknown> } }).wakeLock?.request('screen').catch(() => undefined); } catch { /* optional */ } };
  const reset = () => { setRunning(false); setIdx(0); setSetNo(1); setPhase('ready'); setLeft(5); announced.current = ''; window.speechSynthesis?.cancel(); };
  if (phase === 'done') return <div className="min-h-[80vh] flex items-center justify-center"><div className="card bg-base-200 text-center"><div className="card-body items-center"><CheckCircle2 size={72} className="text-success" /><h2 className="card-title text-2xl">Allenamento completato!</h2><p>Hai concluso {workout.title}. Recupera almeno 48 ore prima della prossima seduta pliometrica.</p><button className="btn btn-primary mt-3" onClick={onExit}>Torna al mese</button></div></div></div>;
  const duration = phase === 'work' ? exercise.work : phase === 'rest' ? exercise.rest : phase === 'ready' ? 5 : 1;
  const pct = Math.max(0, Math.round(left / duration * 100));
  return <div className="min-h-screen flex flex-col gap-4 pb-5"><div className="flex justify-between items-center"><button className="btn btn-ghost btn-sm" onClick={onExit}><ArrowLeft size={18} /> Esci</button><span className="badge badge-outline">{idx + 1}/{workout.exercises.length}</span>{getSpotifyLink() && <button className="btn btn-ghost btn-sm btn-circle" onClick={openSpotify} aria-label="Apri Spotify"><Music size={18} /></button>}</div><div className={`card ${phase === 'work' ? 'bg-primary text-primary-content' : phase === 'rest' ? 'bg-secondary text-secondary-content' : 'bg-base-200'} grow`}><div className="card-body p-5 items-center text-center justify-between"><div><span className="badge badge-lg">{phase === 'ready' ? 'PREPARATI' : phase === 'work' ? 'LAVORO' : 'RECUPERO'}</span><h2 className="text-2xl font-bold mt-3">{exercise.name}</h2><p className="opacity-80">Serie {setNo} di {exercise.sets} · {exercise.prescription}</p></div><MovementAnimation kind={exercise.kind} active={running} id={exercise.id} /><div><div className="font-mono text-7xl font-black tabular-nums">{Math.floor(left / 60)}:{String(left % 60).padStart(2, '0')}</div><progress className="progress w-full mt-3" value={pct} max="100" /><p className="mt-3 font-medium">{exercise.cues.join(' · ')}</p></div></div></div><div className="grid grid-cols-4 gap-2"><button className="btn btn-ghost" onClick={reset}><RotateCcw /></button><button className="btn btn-primary col-span-2 btn-lg" onClick={() => running ? setRunning(false) : start()}>{running ? <><Pause /> PAUSA</> : <><Play /> {left === 5 && idx === 0 ? 'START' : 'RIPRENDI'}</>}</button><button className="btn btn-ghost" onClick={next}><SkipForward /></button></div><p className="text-xs text-center text-base-content/60 flex items-center justify-center gap-1"><Volume2 size={14} /> L’audio viene inviato all’uscita scelta dal telefono, incluse le cuffiette Bluetooth.</p></div>;
};
