import React, { useState } from 'react';
import { ArrowLeft, ChevronDown, ChevronUp, Headphones, Music, Play, ShieldAlert, TimerReset, Weight } from 'lucide-react';
import type { Workout } from '../types';
import { MovementAnimation } from './MovementAnimation';
import { getSpotifyLink, setSpotifyLink } from '../spotify';

interface Props { workout: Workout; onBack: () => void; onStart: () => void; }
export const WorkoutDetail: React.FC<Props> = ({ workout, onBack, onStart }) => {
  const [open, setOpen] = useState(1);
  const [spotify, setSpotify] = useState(getSpotifyLink());
  const saveSpotify = (v: string) => { setSpotify(v); setSpotifyLink(v); };
  return <div className="space-y-4 pb-28"><button className="btn btn-ghost btn-sm" onClick={onBack}><ArrowLeft size={18} /> Programma</button><section className="card bg-primary text-primary-content"><div className="card-body p-5"><div className="flex gap-2"><span className="badge">Settimana {workout.week}</span><span className="badge">Giorno {workout.day}</span></div><h2 className="card-title text-2xl">{workout.title}</h2><p className="text-primary-content/80">{workout.focus} · {workout.duration}</p></div></section><div className="alert bg-base-200 text-sm"><Headphones size={20} /><span>Collega le cuffiette e lascia il volume udibile: la guida annuncia start, esercizio, recupero e serie.</span></div><div className="card bg-base-200"><div className="card-body p-4 gap-2"><div className="flex items-center gap-2 font-semibold text-sm"><Music size={17} /> Musica di sottofondo (facoltativa)</div><p className="text-xs text-base-content/60">Incolla il link di una playlist o brano Spotify. Si apre nell'app Spotify a parte; il timer e la voce guida restano qui.</p><input type="url" inputMode="url" placeholder="https://open.spotify.com/playlist/..." className="input input-bordered input-sm w-full" value={spotify} onChange={e => saveSpotify(e.target.value)} /></div></div><div className="space-y-3">{workout.exercises.map((e,i) => <article key={`${e.id}-${i}`} className="card bg-base-200 overflow-hidden"><button className="card-body p-4 text-left" onClick={() => setOpen(open === i ? -1 : i)}><div className="flex items-center gap-3"><span className="badge badge-primary badge-lg">{i+1}</span><div className="grow"><h3 className="font-semibold">{e.name}</h3><p className="text-sm text-base-content/60">{e.sets} × {e.prescription} · recupero {e.rest}s</p></div>{open === i ? <ChevronUp /> : <ChevronDown />}</div></button>{open === i && <div className="px-4 pb-4 space-y-3"><MovementAnimation kind={e.kind} id={e.id} /><p className="text-sm leading-relaxed">{e.instructions}</p><div className="flex flex-wrap gap-2">{e.cues.map(c => <span key={c} className="badge badge-outline">{c}</span>)}</div>{e.vest && <div className="alert alert-warning text-xs py-2"><Weight size={17} /><span>{e.vest}</span></div>}</div>}</article>)}</div><div className="alert alert-warning text-xs"><ShieldAlert size={20} /><span>Non usare il corpetto se sei alle prime armi, hai dolore o l'atterraggio non è silenzioso e stabile. In caso di problemi articolari o cardiaci, chiedi prima al medico/fisioterapista.</span></div><div className="fixed bottom-0 left-0 right-0 p-4 bg-base-100/95 border-t border-base-300 z-20"><div className="max-w-lg mx-auto"><button className="btn btn-primary btn-lg w-full" onClick={onStart}><Play fill="currentColor" /> START GUIDATO</button><p className="text-center text-[11px] text-base-content/50 mt-1 flex justify-center gap-1 items-center"><TimerReset size={12} /> Timer + voce in cuffia</p></div></div></div>;
};
